/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Marshaled node returned to JS. Mirrors `core::Node` as a napi object so the
 * whole tree crosses the boundary in one return value (full-marshaling mode).
 */
export interface JsNode {
  nodeType: number
  name: string
  value: string
  namespace: string
  publicId: string
  systemId: string
  attrs: Array<JsAttr>
  children: Array<JsNode>
}
export interface JsAttr {
  name: string
  value: string
  prefix: string
}
/** Parse a full HTML document. Boundary crossed exactly once. */
export declare function parse(html: string): JsNode
/**
 * Parse an HTML fragment (innerHTML-style). `context` is the context element:
 * e.g. "body" (default), "td", or namespaced "svg path" / "math ms".
 */
export declare function parseFragment(html: string, context?: string | undefined | null): JsNode
